global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: aegisx
    environment: production

scrape_configs:
  - job_name: aegisx-api
    static_configs:
      - targets: ["api:9100"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  - job_name: node-exporter
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
